version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: yarn install
          command: yarn install
      - run:
          name: test
          command: yarn test

workflows:
  base:
    jobs:
      - test:
          filters:
            branches:
              only:
                - ci