version: 2.1

orbs:
  kaniko-publish: glenjamin/kaniko-publish@0.0.1

jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn install
      - run:
          name: test
          command: yarn test

workflows:
  base:
    jobs:
      - test:
          filters:
            branches:
              only:
                - ci

  build_and_publish_image:
     jobs:
      - docker-publish/publish:
          image: front-service
          tag: latest
          filters:
            branches:
              only:
                - ci
